// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: performance_test_protocol.proto

package ru.spbau.annikura.performance_test;

public final class PerformanceTestProtocol {
  private PerformanceTestProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SortRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:performance_tester.SortRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 arraySize = 1;</code>
     */
    boolean hasArraySize();
    /**
     * <code>required int32 arraySize = 1;</code>
     */
    int getArraySize();

    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    java.util.List<java.lang.Integer> getArrayElementsList();
    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    int getArrayElementsCount();
    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    int getArrayElements(int index);

    /**
     * <code>optional bool isLast = 8;</code>
     */
    boolean hasIsLast();
    /**
     * <code>optional bool isLast = 8;</code>
     */
    boolean getIsLast();
  }
  /**
   * Protobuf type {@code performance_tester.SortRequest}
   */
  public  static final class SortRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:performance_tester.SortRequest)
      SortRequestOrBuilder {
    // Use SortRequest.newBuilder() to construct.
    private SortRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SortRequest() {
      arraySize_ = 0;
      arrayElements_ = java.util.Collections.emptyList();
      isLast_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SortRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              arraySize_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                arrayElements_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              arrayElements_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                arrayElements_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                arrayElements_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 64: {
              bitField0_ |= 0x00000002;
              isLast_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = java.util.Collections.unmodifiableList(arrayElements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.Builder.class);
    }

    private int bitField0_;
    public static final int ARRAYSIZE_FIELD_NUMBER = 1;
    private int arraySize_;
    /**
     * <code>required int32 arraySize = 1;</code>
     */
    public boolean hasArraySize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 arraySize = 1;</code>
     */
    public int getArraySize() {
      return arraySize_;
    }

    public static final int ARRAYELEMENTS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> arrayElements_;
    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getArrayElementsList() {
      return arrayElements_;
    }
    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    public int getArrayElementsCount() {
      return arrayElements_.size();
    }
    /**
     * <code>repeated int32 arrayElements = 2;</code>
     */
    public int getArrayElements(int index) {
      return arrayElements_.get(index);
    }

    public static final int ISLAST_FIELD_NUMBER = 8;
    private boolean isLast_;
    /**
     * <code>optional bool isLast = 8;</code>
     */
    public boolean hasIsLast() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool isLast = 8;</code>
     */
    public boolean getIsLast() {
      return isLast_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasArraySize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, arraySize_);
      }
      for (int i = 0; i < arrayElements_.size(); i++) {
        output.writeInt32(2, arrayElements_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(8, isLast_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, arraySize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arrayElements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(arrayElements_.get(i));
        }
        size += dataSize;
        size += 1 * getArrayElementsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isLast_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest)) {
        return super.equals(obj);
      }
      ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest other = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest) obj;

      boolean result = true;
      result = result && (hasArraySize() == other.hasArraySize());
      if (hasArraySize()) {
        result = result && (getArraySize()
            == other.getArraySize());
      }
      result = result && getArrayElementsList()
          .equals(other.getArrayElementsList());
      result = result && (hasIsLast() == other.hasIsLast());
      if (hasIsLast()) {
        result = result && (getIsLast()
            == other.getIsLast());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasArraySize()) {
        hash = (37 * hash) + ARRAYSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getArraySize();
      }
      if (getArrayElementsCount() > 0) {
        hash = (37 * hash) + ARRAYELEMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArrayElementsList().hashCode();
      }
      if (hasIsLast()) {
        hash = (37 * hash) + ISLAST_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsLast());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code performance_tester.SortRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:performance_tester.SortRequest)
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.Builder.class);
      }

      // Construct using ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        arraySize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arrayElements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        isLast_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortRequest_descriptor;
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest getDefaultInstanceForType() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.getDefaultInstance();
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest build() {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest buildPartial() {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest result = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.arraySize_ = arraySize_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = java.util.Collections.unmodifiableList(arrayElements_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.arrayElements_ = arrayElements_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isLast_ = isLast_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest) {
          return mergeFrom((ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest other) {
        if (other == ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest.getDefaultInstance()) return this;
        if (other.hasArraySize()) {
          setArraySize(other.getArraySize());
        }
        if (!other.arrayElements_.isEmpty()) {
          if (arrayElements_.isEmpty()) {
            arrayElements_ = other.arrayElements_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArrayElementsIsMutable();
            arrayElements_.addAll(other.arrayElements_);
          }
          onChanged();
        }
        if (other.hasIsLast()) {
          setIsLast(other.getIsLast());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArraySize()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int arraySize_ ;
      /**
       * <code>required int32 arraySize = 1;</code>
       */
      public boolean hasArraySize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 arraySize = 1;</code>
       */
      public int getArraySize() {
        return arraySize_;
      }
      /**
       * <code>required int32 arraySize = 1;</code>
       */
      public Builder setArraySize(int value) {
        bitField0_ |= 0x00000001;
        arraySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arraySize = 1;</code>
       */
      public Builder clearArraySize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        arraySize_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> arrayElements_ = java.util.Collections.emptyList();
      private void ensureArrayElementsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = new java.util.ArrayList<java.lang.Integer>(arrayElements_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getArrayElementsList() {
        return java.util.Collections.unmodifiableList(arrayElements_);
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public int getArrayElementsCount() {
        return arrayElements_.size();
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public int getArrayElements(int index) {
        return arrayElements_.get(index);
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public Builder setArrayElements(
          int index, int value) {
        ensureArrayElementsIsMutable();
        arrayElements_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public Builder addArrayElements(int value) {
        ensureArrayElementsIsMutable();
        arrayElements_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public Builder addAllArrayElements(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrayElementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arrayElements_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 2;</code>
       */
      public Builder clearArrayElements() {
        arrayElements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private boolean isLast_ ;
      /**
       * <code>optional bool isLast = 8;</code>
       */
      public boolean hasIsLast() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool isLast = 8;</code>
       */
      public boolean getIsLast() {
        return isLast_;
      }
      /**
       * <code>optional bool isLast = 8;</code>
       */
      public Builder setIsLast(boolean value) {
        bitField0_ |= 0x00000004;
        isLast_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLast = 8;</code>
       */
      public Builder clearIsLast() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isLast_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:performance_tester.SortRequest)
    }

    // @@protoc_insertion_point(class_scope:performance_tester.SortRequest)
    private static final ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest();
    }

    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SortRequest>
        PARSER = new com.google.protobuf.AbstractParser<SortRequest>() {
      public SortRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SortRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SortRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SortRequest> getParserForType() {
      return PARSER;
    }

    public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SortResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:performance_tester.SortResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 arraySize = 3;</code>
     */
    boolean hasArraySize();
    /**
     * <code>required int32 arraySize = 3;</code>
     */
    int getArraySize();

    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    java.util.List<java.lang.Integer> getArrayElementsList();
    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    int getArrayElementsCount();
    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    int getArrayElements(int index);

    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    boolean hasStats();
    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getStats();
    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder getStatsOrBuilder();

    /**
     * <code>optional string errorMessage = 9;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code performance_tester.SortResponse}
   */
  public  static final class SortResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:performance_tester.SortResponse)
      SortResponseOrBuilder {
    // Use SortResponse.newBuilder() to construct.
    private SortResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SortResponse() {
      arraySize_ = 0;
      arrayElements_ = java.util.Collections.emptyList();
      errorMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SortResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              arraySize_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                arrayElements_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              arrayElements_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                arrayElements_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                arrayElements_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 58: {
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = stats_.toBuilder();
              }
              stats_ = input.readMessage(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(stats_);
                stats_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              errorMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = java.util.Collections.unmodifiableList(arrayElements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Builder.class);
    }

    public interface StatisticsOrBuilder extends
        // @@protoc_insertion_point(interface_extends:performance_tester.SortResponse.Statistics)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 requestTime = 5;</code>
       */
      boolean hasRequestTime();
      /**
       * <code>required int64 requestTime = 5;</code>
       */
      long getRequestTime();

      /**
       * <code>required int64 sortTime = 6;</code>
       */
      boolean hasSortTime();
      /**
       * <code>required int64 sortTime = 6;</code>
       */
      long getSortTime();
    }
    /**
     * Protobuf type {@code performance_tester.SortResponse.Statistics}
     */
    public  static final class Statistics extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:performance_tester.SortResponse.Statistics)
        StatisticsOrBuilder {
      // Use Statistics.newBuilder() to construct.
      private Statistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Statistics() {
        requestTime_ = 0L;
        sortTime_ = 0L;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Statistics(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 40: {
                bitField0_ |= 0x00000001;
                requestTime_ = input.readInt64();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000002;
                sortTime_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_Statistics_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_Statistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder.class);
      }

      private int bitField0_;
      public static final int REQUESTTIME_FIELD_NUMBER = 5;
      private long requestTime_;
      /**
       * <code>required int64 requestTime = 5;</code>
       */
      public boolean hasRequestTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 requestTime = 5;</code>
       */
      public long getRequestTime() {
        return requestTime_;
      }

      public static final int SORTTIME_FIELD_NUMBER = 6;
      private long sortTime_;
      /**
       * <code>required int64 sortTime = 6;</code>
       */
      public boolean hasSortTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 sortTime = 6;</code>
       */
      public long getSortTime() {
        return sortTime_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasRequestTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasSortTime()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(5, requestTime_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(6, sortTime_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, requestTime_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(6, sortTime_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics)) {
          return super.equals(obj);
        }
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics other = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics) obj;

        boolean result = true;
        result = result && (hasRequestTime() == other.hasRequestTime());
        if (hasRequestTime()) {
          result = result && (getRequestTime()
              == other.getRequestTime());
        }
        result = result && (hasSortTime() == other.hasSortTime());
        if (hasSortTime()) {
          result = result && (getSortTime()
              == other.getSortTime());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (hasRequestTime()) {
          hash = (37 * hash) + REQUESTTIME_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getRequestTime());
        }
        if (hasSortTime()) {
          hash = (37 * hash) + SORTTIME_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getSortTime());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code performance_tester.SortResponse.Statistics}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:performance_tester.SortResponse.Statistics)
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_Statistics_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_Statistics_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder.class);
        }

        // Construct using ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          requestTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          sortTime_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_Statistics_descriptor;
        }

        public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getDefaultInstanceForType() {
          return ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance();
        }

        public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics build() {
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics buildPartial() {
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics result = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.requestTime_ = requestTime_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.sortTime_ = sortTime_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics) {
            return mergeFrom((ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics other) {
          if (other == ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance()) return this;
          if (other.hasRequestTime()) {
            setRequestTime(other.getRequestTime());
          }
          if (other.hasSortTime()) {
            setSortTime(other.getSortTime());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRequestTime()) {
            return false;
          }
          if (!hasSortTime()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long requestTime_ ;
        /**
         * <code>required int64 requestTime = 5;</code>
         */
        public boolean hasRequestTime() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 requestTime = 5;</code>
         */
        public long getRequestTime() {
          return requestTime_;
        }
        /**
         * <code>required int64 requestTime = 5;</code>
         */
        public Builder setRequestTime(long value) {
          bitField0_ |= 0x00000001;
          requestTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 requestTime = 5;</code>
         */
        public Builder clearRequestTime() {
          bitField0_ = (bitField0_ & ~0x00000001);
          requestTime_ = 0L;
          onChanged();
          return this;
        }

        private long sortTime_ ;
        /**
         * <code>required int64 sortTime = 6;</code>
         */
        public boolean hasSortTime() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 sortTime = 6;</code>
         */
        public long getSortTime() {
          return sortTime_;
        }
        /**
         * <code>required int64 sortTime = 6;</code>
         */
        public Builder setSortTime(long value) {
          bitField0_ |= 0x00000002;
          sortTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 sortTime = 6;</code>
         */
        public Builder clearSortTime() {
          bitField0_ = (bitField0_ & ~0x00000002);
          sortTime_ = 0L;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:performance_tester.SortResponse.Statistics)
      }

      // @@protoc_insertion_point(class_scope:performance_tester.SortResponse.Statistics)
      private static final ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics();
      }

      public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Statistics>
          PARSER = new com.google.protobuf.AbstractParser<Statistics>() {
        public Statistics parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Statistics(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Statistics> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Statistics> getParserForType() {
        return PARSER;
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int ARRAYSIZE_FIELD_NUMBER = 3;
    private int arraySize_;
    /**
     * <code>required int32 arraySize = 3;</code>
     */
    public boolean hasArraySize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 arraySize = 3;</code>
     */
    public int getArraySize() {
      return arraySize_;
    }

    public static final int ARRAYELEMENTS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> arrayElements_;
    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getArrayElementsList() {
      return arrayElements_;
    }
    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    public int getArrayElementsCount() {
      return arrayElements_.size();
    }
    /**
     * <code>repeated int32 arrayElements = 4;</code>
     */
    public int getArrayElements(int index) {
      return arrayElements_.get(index);
    }

    public static final int STATS_FIELD_NUMBER = 7;
    private ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics stats_;
    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    public boolean hasStats() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getStats() {
      return stats_ == null ? ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance() : stats_;
    }
    /**
     * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
     */
    public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder getStatsOrBuilder() {
      return stats_ == null ? ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance() : stats_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 9;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string errorMessage = 9;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasArraySize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasStats()) {
        if (!getStats().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(3, arraySize_);
      }
      for (int i = 0; i < arrayElements_.size(); i++) {
        output.writeInt32(4, arrayElements_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(7, getStats());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, errorMessage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, arraySize_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < arrayElements_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(arrayElements_.get(i));
        }
        size += dataSize;
        size += 1 * getArrayElementsList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getStats());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, errorMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse)) {
        return super.equals(obj);
      }
      ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse other = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse) obj;

      boolean result = true;
      result = result && (hasArraySize() == other.hasArraySize());
      if (hasArraySize()) {
        result = result && (getArraySize()
            == other.getArraySize());
      }
      result = result && getArrayElementsList()
          .equals(other.getArrayElementsList());
      result = result && (hasStats() == other.hasStats());
      if (hasStats()) {
        result = result && getStats()
            .equals(other.getStats());
      }
      result = result && (hasErrorMessage() == other.hasErrorMessage());
      if (hasErrorMessage()) {
        result = result && getErrorMessage()
            .equals(other.getErrorMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasArraySize()) {
        hash = (37 * hash) + ARRAYSIZE_FIELD_NUMBER;
        hash = (53 * hash) + getArraySize();
      }
      if (getArrayElementsCount() > 0) {
        hash = (37 * hash) + ARRAYELEMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getArrayElementsList().hashCode();
      }
      if (hasStats()) {
        hash = (37 * hash) + STATS_FIELD_NUMBER;
        hash = (53 * hash) + getStats().hashCode();
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code performance_tester.SortResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:performance_tester.SortResponse)
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.class, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Builder.class);
      }

      // Construct using ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        arraySize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arrayElements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        if (statsBuilder_ == null) {
          stats_ = null;
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.internal_static_performance_tester_SortResponse_descriptor;
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse getDefaultInstanceForType() {
        return ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.getDefaultInstance();
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse build() {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse buildPartial() {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse result = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.arraySize_ = arraySize_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = java.util.Collections.unmodifiableList(arrayElements_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.arrayElements_ = arrayElements_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (statsBuilder_ == null) {
          result.stats_ = stats_;
        } else {
          result.stats_ = statsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse) {
          return mergeFrom((ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse other) {
        if (other == ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.getDefaultInstance()) return this;
        if (other.hasArraySize()) {
          setArraySize(other.getArraySize());
        }
        if (!other.arrayElements_.isEmpty()) {
          if (arrayElements_.isEmpty()) {
            arrayElements_ = other.arrayElements_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArrayElementsIsMutable();
            arrayElements_.addAll(other.arrayElements_);
          }
          onChanged();
        }
        if (other.hasStats()) {
          mergeStats(other.getStats());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000008;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasArraySize()) {
          return false;
        }
        if (hasStats()) {
          if (!getStats().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int arraySize_ ;
      /**
       * <code>required int32 arraySize = 3;</code>
       */
      public boolean hasArraySize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 arraySize = 3;</code>
       */
      public int getArraySize() {
        return arraySize_;
      }
      /**
       * <code>required int32 arraySize = 3;</code>
       */
      public Builder setArraySize(int value) {
        bitField0_ |= 0x00000001;
        arraySize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 arraySize = 3;</code>
       */
      public Builder clearArraySize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        arraySize_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> arrayElements_ = java.util.Collections.emptyList();
      private void ensureArrayElementsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          arrayElements_ = new java.util.ArrayList<java.lang.Integer>(arrayElements_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getArrayElementsList() {
        return java.util.Collections.unmodifiableList(arrayElements_);
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public int getArrayElementsCount() {
        return arrayElements_.size();
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public int getArrayElements(int index) {
        return arrayElements_.get(index);
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public Builder setArrayElements(
          int index, int value) {
        ensureArrayElementsIsMutable();
        arrayElements_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public Builder addArrayElements(int value) {
        ensureArrayElementsIsMutable();
        arrayElements_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public Builder addAllArrayElements(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrayElementsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arrayElements_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 arrayElements = 4;</code>
       */
      public Builder clearArrayElements() {
        arrayElements_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics stats_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder> statsBuilder_;
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public boolean hasStats() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics getStats() {
        if (statsBuilder_ == null) {
          return stats_ == null ? ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance() : stats_;
        } else {
          return statsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public Builder setStats(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stats_ = value;
          onChanged();
        } else {
          statsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public Builder setStats(
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder builderForValue) {
        if (statsBuilder_ == null) {
          stats_ = builderForValue.build();
          onChanged();
        } else {
          statsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public Builder mergeStats(ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics value) {
        if (statsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              stats_ != null &&
              stats_ != ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance()) {
            stats_ =
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.newBuilder(stats_).mergeFrom(value).buildPartial();
          } else {
            stats_ = value;
          }
          onChanged();
        } else {
          statsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public Builder clearStats() {
        if (statsBuilder_ == null) {
          stats_ = null;
          onChanged();
        } else {
          statsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder getStatsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getStatsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder getStatsOrBuilder() {
        if (statsBuilder_ != null) {
          return statsBuilder_.getMessageOrBuilder();
        } else {
          return stats_ == null ?
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.getDefaultInstance() : stats_;
        }
      }
      /**
       * <code>optional .performance_tester.SortResponse.Statistics stats = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder> 
          getStatsFieldBuilder() {
        if (statsBuilder_ == null) {
          statsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.Statistics.Builder, ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse.StatisticsOrBuilder>(
                  getStats(),
                  getParentForChildren(),
                  isClean());
          stats_ = null;
        }
        return statsBuilder_;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorMessage = 9;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:performance_tester.SortResponse)
    }

    // @@protoc_insertion_point(class_scope:performance_tester.SortResponse)
    private static final ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse();
    }

    public static ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SortResponse>
        PARSER = new com.google.protobuf.AbstractParser<SortResponse>() {
      public SortResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SortResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SortResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SortResponse> getParserForType() {
      return PARSER;
    }

    public ru.spbau.annikura.performance_test.PerformanceTestProtocol.SortResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_performance_tester_SortRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_performance_tester_SortRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_performance_tester_SortResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_performance_tester_SortResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_performance_tester_SortResponse_Statistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_performance_tester_SortResponse_Statistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037performance_test_protocol.proto\022\022perfo" +
      "rmance_tester\"G\n\013SortRequest\022\021\n\tarraySiz" +
      "e\030\001 \002(\005\022\025\n\rarrayElements\030\002 \003(\005\022\016\n\006isLast" +
      "\030\010 \001(\010\"\277\001\n\014SortResponse\022\021\n\tarraySize\030\003 \002" +
      "(\005\022\025\n\rarrayElements\030\004 \003(\005\022:\n\005stats\030\007 \001(\013" +
      "2+.performance_tester.SortResponse.Stati" +
      "stics\022\024\n\014errorMessage\030\t \001(\t\0323\n\nStatistic" +
      "s\022\023\n\013requestTime\030\005 \002(\003\022\020\n\010sortTime\030\006 \002(\003" +
      "B$\n\"ru.spbau.annikura.performance_test"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_performance_tester_SortRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_performance_tester_SortRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_performance_tester_SortRequest_descriptor,
        new java.lang.String[] { "ArraySize", "ArrayElements", "IsLast", });
    internal_static_performance_tester_SortResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_performance_tester_SortResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_performance_tester_SortResponse_descriptor,
        new java.lang.String[] { "ArraySize", "ArrayElements", "Stats", "ErrorMessage", });
    internal_static_performance_tester_SortResponse_Statistics_descriptor =
      internal_static_performance_tester_SortResponse_descriptor.getNestedTypes().get(0);
    internal_static_performance_tester_SortResponse_Statistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_performance_tester_SortResponse_Statistics_descriptor,
        new java.lang.String[] { "RequestTime", "SortTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
